version: '3.8'

services:
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET}
      - SERVICE_API_KEY=${SERVICE_API_KEY}
    restart: unless-stopped
    networks:
      - classecon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - AUTH_SERVICE_URL=http://auth-service:4001
      - SERVICE_API_KEY=${SERVICE_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - auth-service
    restart: unless-stopped
    networks:
      - classecon-network

networks:
  classecon-network:
    driver: bridge
