[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/index.html"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
